# installer for fab
# Copyright 2017-2019 Matthew Wall
# Distributed under the terms of the GNU Public License (GPLv3)

from weecfg.extension import ExtensionInstaller

def loader():
    return FabInstaller()

class FabInstaller(ExtensionInstaller):
    def __init__(self):
        super(FabInstaller, self).__init__(
            version="0.2",
            name='fab',
            description='Just a few data points to help you with the day.',
            author="Matthew Wall",
            author_email="mwall@users.sourceforge.net",
            config={
                'StdReport': {
                    'fab': {
                        'skin':'fab',
                        'HTML_ROOT':'fab'}}},
            files=[('skins/fab',
                    ['skins/fab/conditions.html.tmpl',
                     'skins/fab/cookie.js',
                     'skins/fab/fab.css',
                     'skins/fab/favicon.ico',
                     'skins/fab/forecast_compact.css',
                     'skins/fab/forecast_compact.inc',
                     'skins/fab/forecast_iconic.css',
                     'skins/fab/forecast_iconic.inc',
                     'skins/fab/forecast_strip.css',
                     'skins/fab/forecast_strip.inc',
                     'skins/fab/forecast_table.css',
                     'skins/fab/forecast_table.inc',
                     'skins/fab/index.html.tmpl',
                     'skins/fab/skin.conf']),
                   ('skins/fab/font',
                    ['skins/fab/font/OpenSans-Bold.ttf',
                     'skins/fab/font/OpenSans.woff',
                     'skins/fab/font/OpenSans.woff2',
                     'skins/fab/font/OpenSans-Regular.ttf']),
                   ('skins/fab/icons',
                    ['skins/fab/icons/AF.png',
                     'skins/fab/icons/B1.png',
                     'skins/fab/icons/B1n.png',
                     'skins/fab/icons/B2.png',
                     'skins/fab/icons/B2n.png',
                     'skins/fab/icons/BD.png',
                     'skins/fab/icons/BK.png',
                     'skins/fab/icons/BKn.png',
                     'skins/fab/icons/BS.png',
                     'skins/fab/icons/CL.png',
                     'skins/fab/icons/CLn.png',
                     'skins/fab/icons/E.png',
                     'skins/fab/icons/F+.png',
                     'skins/fab/icons/F.png',
                     'skins/fab/icons/FW.png',
                     'skins/fab/icons/FWn.png',
                     'skins/fab/icons/H.png',
                     'skins/fab/icons/K.png',
                     'skins/fab/icons/N.png',
                     'skins/fab/icons/NE.png',
                     'skins/fab/icons/NW.png',
                     'skins/fab/icons/OV.png',
                     'skins/fab/icons/OVn.png',
                     'skins/fab/icons/PF+.png',
                     'skins/fab/icons/PF.png',
                     'skins/fab/icons/S.png',
                     'skins/fab/icons/SC.png',
                     'skins/fab/icons/SCn.png',
                     'skins/fab/icons/SE.png',
                     'skins/fab/icons/SW.png',
                     'skins/fab/icons/W.png',
                     'skins/fab/icons/blizzard.png',
                     'skins/fab/icons/drizzle.png',
                     'skins/fab/icons/flag-yellow.png',
                     'skins/fab/icons/flag.png',
                     'skins/fab/icons/flurries.png',
                     'skins/fab/icons/frzngdrzl.png',
                     'skins/fab/icons/moon.png',
                     'skins/fab/icons/moonphase.png',
                     'skins/fab/icons/moonrise.png',
                     'skins/fab/icons/moonriseset.png',
                     'skins/fab/icons/moonset.png',
                     'skins/fab/icons/pop.png',
                     'skins/fab/icons/rain.png',
                     'skins/fab/icons/raindrop.png',
                     'skins/fab/icons/rainshwrs.png',
                     'skins/fab/icons/raintorrent.png',
                     'skins/fab/icons/sleet.png',
                     'skins/fab/icons/snow.png',
                     'skins/fab/icons/snowflake.png',
                     'skins/fab/icons/snowshwrs.png',
                     'skins/fab/icons/sprinkles.png',
                     'skins/fab/icons/sun.png',
                     'skins/fab/icons/sunmoon.png',
                     'skins/fab/icons/sunrise.png',
                     'skins/fab/icons/sunriseset.png',
                     'skins/fab/icons/sunset.png',
                     'skins/fab/icons/tE.png',
                     'skins/fab/icons/tENE.png',
                     'skins/fab/icons/tESE.png',
                     'skins/fab/icons/tN.png',
                     'skins/fab/icons/tNE.png',
                     'skins/fab/icons/tNNE.png',
                     'skins/fab/icons/tNNW.png',
                     'skins/fab/icons/tNW.png',
                     'skins/fab/icons/tS.png',
                     'skins/fab/icons/tSE.png',
                     'skins/fab/icons/tSSE.png',
                     'skins/fab/icons/tSSW.png',
                     'skins/fab/icons/tSW.png',
                     'skins/fab/icons/tW.png',
                     'skins/fab/icons/tWNW.png',
                     'skins/fab/icons/tWSW.png',
                     'skins/fab/icons/thermometer-blue.png',
                     'skins/fab/icons/thermometer-dewpoint.png',
                     'skins/fab/icons/thermometer-red.png',
                     'skins/fab/icons/thermometer.png',
                     'skins/fab/icons/triangle-down.png',
                     'skins/fab/icons/triangle-right.png',
                     'skins/fab/icons/tstms.png',
                     'skins/fab/icons/water.png']),
                   ]
            )
